name: pytorch
channels:
        - defaults
        - conda-forge
        - pytorch
dependencies:
        - jupyter
        - jupyterlab
        - ipywidgets
        - pylint
        - rope
        - nodejs
        - numpy
        - scipy
        - pytorch>=1.6
        - torchvision
        - matplotlib
        - graphql-core=2.0
